# Directories arguments
#data_dir: "citykitti_2stream_sms_mine"
data_dir: "kitti_2stream_sq_4"
exp_dir:  "fcn8s_2streamcitykitti_shufflenet_3"
out_dir:  "fcn8s_2streamcitykitti_shufflenet_sq_4"
#data_dir: "vivid_2streamwarp_darpa"
#exp_dir:  "fcn8s_2streamwarp_shufflenet"
#out_dir:  "fcn8s_2streamwarp_shufflenet"

# Data arguments
img_height:   384
img_width:    1248
num_channels: 3
num_classes:  2

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: True
data_mode: "test"
save_every: 10
test_every: 10
max_to_keep: 1
weighted_loss: True
random_cropping: False
freeze_encoder: False

# Models arguments
batchnorm_enabled: True
num_groups: 3
learning_rate:   0.0001
weight_decay: 5e-4
bias: 0.0
pretrained_path: "pretrained_weights/shufflenet_weights.pkl"

# Misc arguments
verbose: False

