# Directories arguments
data_dir: "citykitti_2stream_sms"
exp_dir:  "fcn8s_2streamcitykitti_mobilenet"
out_dir:  "fcn8s_2streamcitykitti_mobilenet"

# Data arguments
img_height:   384
img_width:    1248
num_channels: 3
num_classes:  2

# Train arguments
num_epochs: 200
batch_size: 4
shuffle: True
data_mode: "experiment"
save_every: 10
test_every: 10
max_to_keep: 1
weighted_loss: True
random_cropping: False
freeze_encoder: False

# Models arguments
batchnorm_enabled: True
learning_rate:   0.0001
weight_decay: 5e-4
bias: 0.0
pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

