# Directories arguments
data_dir: "citykitti_2stream_sms_test"
exp_dir:  "fcn8s_2stream_vivid_shufflenet_nchw"
out_dir:  "fcn8s_2stream_vivid_shufflenet_nchw"

# Data arguments
img_height:   360 #384
img_width:    640 #768 #1248
num_channels: 3
num_classes:  2

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: True
data_mode: "test"
save_every: 5
test_every: 5
max_to_keep: 1
weighted_loss: True
random_cropping: False
freeze_encoder: False

# Models arguments
batchnorm_enabled: True
num_groups: 3
learning_rate:   0.0001
weight_decay: 5e-4
bias: 0.0
pretrained_path: "pretrained_weights/shufflenet_cityscapes.pkl"

# Misc arguments
verbose: False

